package com.cmti.analytics.app.station.hbase.domain.bean;

import com.cmti.analytics.util.ObjectUtil;
import com.cmti.analytics.app.station.hbase.domain.mapping.RecordSigMapping;

//Do not edit this file. This file is auto generated by GenSource.

public class RecordSigBean extends RecordSigMapping {

//key
	public void setId(Long id){
		this.id = id;
	}

	public Long getId(){
		return id;
	}
	

//field
	public void setEventDate(java.util.Date eventDate){
		boolean updated = !ObjectUtil.equals(this.eventDate, eventDate);
		if(updated){
			this.eventDate = eventDate;
			setDirty("eventDate");
		}
	}

	public java.util.Date getEventDate(){
		return eventDate;
	}
 	public void setImsi(String imsi){
		boolean updated = !ObjectUtil.equals(this.imsi, imsi);
		if(updated){
			this.imsi = imsi;
			setDirty("imsi");
		}
	}

	public String getImsi(){
		return imsi;
	}
 	public void setSigSession(String sigSession){
		boolean updated = !ObjectUtil.equals(this.sigSession, sigSession);
		if(updated){
			this.sigSession = sigSession;
			setDirty("sigSession");
		}
	}

	public String getSigSession(){
		return sigSession;
	}
 	public void setSubSession(Integer subSession){
		boolean updated = !ObjectUtil.equals(this.subSession, subSession);
		if(updated){
			this.subSession = subSession;
			setDirty("subSession");
		}
	}

	public Integer getSubSession(){
		return subSession;
	}
 	public void setEventType(Integer eventType){
		boolean updated = !ObjectUtil.equals(this.eventType, eventType);
		if(updated){
			this.eventType = eventType;
			setDirty("eventType");
		}
	}

	public Integer getEventType(){
		return eventType;
	}
 	public void setLac(Integer lac){
		boolean updated = !ObjectUtil.equals(this.lac, lac);
		if(updated){
			this.lac = lac;
			setDirty("lac");
		}
	}

	public Integer getLac(){
		return lac;
	}
 	public void setCell(Integer cell){
		boolean updated = !ObjectUtil.equals(this.cell, cell);
		if(updated){
			this.cell = cell;
			setDirty("cell");
		}
	}

	public Integer getCell(){
		return cell;
	}
 	public void setPcu(Integer pcu){
		boolean updated = !ObjectUtil.equals(this.pcu, pcu);
		if(updated){
			this.pcu = pcu;
			setDirty("pcu");
		}
	}

	public Integer getPcu(){
		return pcu;
	}
 	public void setRac(Integer rac){
		boolean updated = !ObjectUtil.equals(this.rac, rac);
		if(updated){
			this.rac = rac;
			setDirty("rac");
		}
	}

	public Integer getRac(){
		return rac;
	}
 	public void setResult(Integer result){
		boolean updated = !ObjectUtil.equals(this.result, result);
		if(updated){
			this.result = result;
			setDirty("result");
		}
	}

	public Integer getResult(){
		return result;
	}
 	public void setFailReason(Integer failReason){
		boolean updated = !ObjectUtil.equals(this.failReason, failReason);
		if(updated){
			this.failReason = failReason;
			setDirty("failReason");
		}
	}

	public Integer getFailReason(){
		return failReason;
	}
 	public void setSigDuration(Integer sigDuration){
		boolean updated = !ObjectUtil.equals(this.sigDuration, sigDuration);
		if(updated){
			this.sigDuration = sigDuration;
			setDirty("sigDuration");
		}
	}

	public Integer getSigDuration(){
		return sigDuration;
	}
 	public void setChannelType(Integer channelType){
		boolean updated = !ObjectUtil.equals(this.channelType, channelType);
		if(updated){
			this.channelType = channelType;
			setDirty("channelType");
		}
	}

	public Integer getChannelType(){
		return channelType;
	}
 	public void setBusinessType(Integer businessType){
		boolean updated = !ObjectUtil.equals(this.businessType, businessType);
		if(updated){
			this.businessType = businessType;
			setDirty("businessType");
		}
	}

	public Integer getBusinessType(){
		return businessType;
	}
 	public void setApn(String apn){
		boolean updated = !ObjectUtil.equals(this.apn, apn);
		if(updated){
			this.apn = apn;
			setDirty("apn");
		}
	}

	public String getApn(){
		return apn;
	}
 	public void setApnIpv4(String apnIpv4){
		boolean updated = !ObjectUtil.equals(this.apnIpv4, apnIpv4);
		if(updated){
			this.apnIpv4 = apnIpv4;
			setDirty("apnIpv4");
		}
	}

	public String getApnIpv4(){
		return apnIpv4;
	}
 	public void setHour(Integer hour){
		boolean updated = !ObjectUtil.equals(this.hour, hour);
		if(updated){
			this.hour = hour;
			setDirty("hour");
		}
	}

	public Integer getHour(){
		return hour;
	}
  	
	@Override
	public String toString(){
		return "RecordSigBean(" + " id="+ id + ")";
	}
	
}