package com.cmti.analytics.app.station.hbase.domain.bean;

import com.cmti.analytics.util.ObjectUtil;
import com.cmti.analytics.app.station.hbase.domain.mapping.StationMapping;

//Do not edit this file. This file is auto generated by GenSource.

public class StationBean extends StationMapping {

//key
	public void setId(Integer id){
		this.id = id;
	}

	public Integer getId(){
		return id;
	}
	

//field
	public void setBsc(String bsc){
		boolean updated = !ObjectUtil.equals(this.bsc, bsc);
		if(updated){
			this.bsc = bsc;
			setDirty("bsc");
		}
	}

	public String getBsc(){
		return bsc;
	}
 	public void setCgi(String cgi){
		boolean updated = !ObjectUtil.equals(this.cgi, cgi);
		if(updated){
			this.cgi = cgi;
			setDirty("cgi");
		}
	}

	public String getCgi(){
		return cgi;
	}
 	public void setLongitude(Double longitude){
		boolean updated = !ObjectUtil.equals(this.longitude, longitude);
		if(updated){
			this.longitude = longitude;
			setDirty("longitude");
		}
	}

	public Double getLongitude(){
		return longitude;
	}
 	public void setLatitude(Double latitude){
		boolean updated = !ObjectUtil.equals(this.latitude, latitude);
		if(updated){
			this.latitude = latitude;
			setDirty("latitude");
		}
	}

	public Double getLatitude(){
		return latitude;
	}
 	public void setType(String type){
		boolean updated = !ObjectUtil.equals(this.type, type);
		if(updated){
			this.type = type;
			setDirty("type");
		}
	}

	public String getType(){
		return type;
	}
 	public void setLac(Integer lac){
		boolean updated = !ObjectUtil.equals(this.lac, lac);
		if(updated){
			this.lac = lac;
			setDirty("lac");
		}
	}

	public Integer getLac(){
		return lac;
	}
 	public void setCi(Integer ci){
		boolean updated = !ObjectUtil.equals(this.ci, ci);
		if(updated){
			this.ci = ci;
			setDirty("ci");
		}
	}

	public Integer getCi(){
		return ci;
	}
 	public void setAngle(Integer angle){
		boolean updated = !ObjectUtil.equals(this.angle, angle);
		if(updated){
			this.angle = angle;
			setDirty("angle");
		}
	}

	public Integer getAngle(){
		return angle;
	}
 	public void setRoom(Boolean room){
		boolean updated = !ObjectUtil.equals(this.room, room);
		if(updated){
			this.room = room;
			setDirty("room");
		}
	}

	public Boolean getRoom(){
		return room;
	}
  	
	@Override
	public String toString(){
		return "StationBean(" + " id="+ id + ")";
	}
	
}